### ISSUE TITLE
Add examples of Rules embedded in YAML documents

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqassistant#415]
### Task Description

The reference of jQA should contain some examples of jQA rules embedded in YAML documents.

### Definition of Done for the Implementers
- [ ] We got a final feedback from the reporting user
- [ ] Documentation has been written
- [ ] Added a note on the new feature to the release notes
