### ISSUE TITLE
Replace the GraphGenerationFailedException by an exception from the Core Framework

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqassistant#465]
### Task Description

**As developer** of the YAML II plugin for jQA,
**I would like** to replace the `GraphGenerationFailedException` by a better exception, provided by the Core Framework of jQA,
**so that** we have more consistent design.

### Additional Resources 

* jQAssistant/jqassistant#416

### Definition of Done for the Implementers
- [ ] Unittests have been written
- [ ] Integration tests have been written
- [ ] Test coverage is the same or even better then before

**Comment by obfischer** [comment]
Would anyone object if we closed this issue after all these years?
