### ISSUE TITLE
Index property of an item in a sequence should be moved to the connected relation

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqassistant#466]
### Task Description

**As developer** of the YAML II plugin for jQA,
**I would like** to have the index of any kind of  item in a sequence to be an property of the relation between the containing sequence and the item of the sequence,
**so that** we have this information in the right place.

### Rationale

The index information is a property of the relation and not a property of the item, as the item can also occur in an non-index context in a document. Furthermore this would be also helpful if we support ordered maps.

### Definition of Done for the Implementers
- [ ] Unittests have been written and existing adapted
- [ ] Integration tests have been written an existing adapted
- [ ] Test coverage is the same or even better then before
- [ ] Documentation has been written and existing updated
- [ ] Added a note on the new feature to the release notes

**Comment by obfischer** [comment]
Would anyone object if we closed this issue after all these years?
